sh NMT/sbatch/TEST/an-en/all_NMT.sh
sh NMT/sbatch/TEST/djk-en/all_NMT.sh
sh NMT/sbatch/TEST/bem-en/all_NMT.sh
sh NMT/sbatch/TEST/bho-as/all_NMT.sh
sh NMT/sbatch/TEST/bho-hi/all_NMT.sh
sh NMT/sbatch/TEST/ewe-en/all_NMT.sh
sh NMT/sbatch/TEST/fon-fr/all_NMT.sh
sh NMT/sbatch/TEST/mfe-en/all_NMT.sh
sh NMT/sbatch/TEST/as-hi/all_NMT.sh
