# Outputs
save: /home/hatch5o6/nobackup/archive/CognateMT/PredictCognates/FINETUNE.SC_fr2mfe.en->mfe.en
test_checkpoint:
remove_special_toks: True
verbose: False
little_verbose: True

# Finetune?
from_pretrained: /home/hatch5o6/nobackup/archive/CognateMT/PredictCognates/PRETRAIN.SC_fr2mfe.en.10M_TRIAL_s=1000

# data
train_data: data/FINETUNE.mfe.en/train.csv
val_data: data/mfe-en_dev_test/val.csv
test_data: data/mfe-en_dev_test/test.csv
append_src_token: False
append_tgt_token: False
upsample: False

# tokenizers
src_spm: /home/hatch5o6/nobackup/archive/CognateMT/spm_models/SC_fr2mfe.mfe/SC_fr2mfe.mfe
tgt_spm: /home/hatch5o6/nobackup/archive/CognateMT/spm_models/en_again/en

# training
seed: 1000

train_batch_size: 128
val_batch_size: 128
test_batch_size: 128

early_stop: 10
save_top_k: 2
max_epochs: 1000
val_interval: 0.2 # 5 times / epoch

learning_rate: 0.00002

device: cuda

# config
encoder_layers: 6
encoder_attention_heads: 8
encoder_ffn_dim: 2048
encoder_layerdrop: 0.0

decoder_layers: 6
decoder_attention_heads: 8
decoder_ffn_dim: 2048
decoder_layerdrop: 0.0

max_position_embeddings: 512
max_length: 512
d_model: 512
dropout: 0.1
activation_function: gelu