sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/AUGMENT.SC_fr2mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/AUGMENT.mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/CHAR-PRETRAIN.SC_fr2mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/CHAR-PRETRAIN.fr-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/NMT.mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/PRETRAIN.SC_fr2mfe-en.TEST-mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/PRETRAIN.SC_fr2mfe-en.no_grad_clip.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/PRETRAIN.SC_fr2mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/PRETRAIN.fr-en.TEST-mfe-en.sh
sbatch /home/hatch5o6/Cognate/code/NMT/sbatch/TRAIN/mfe-en_chosen_0/PRETRAIN.fr-en.sh
