activation_function: gelu
append_src_token: false
append_tgt_token: false
d_model: 512
decoder_attention_heads: 8
decoder_ffn_dim: 2048
decoder_layerdrop: 0.0
decoder_layers: 6
device: cuda
dropout: 0.1
early_stop: 10
encoder_attention_heads: 8
encoder_ffn_dim: 2048
encoder_layerdrop: 0.0
encoder_layers: 6
from_pretrained: null
learning_rate: 0.0005
little_verbose: true
max_length: 512
max_position_embeddings: 512
max_steps: 100000
n_gpus: 4
qos: dw87
remove_special_toks: true
save: /home/hatch5o6/nobackup/archive/CognateMT/PredictCognates/mfe-en/PRETRAIN.fr-en
save_top_k: 10
sc_model_id: null
seed: 1000
spm: /home/hatch5o6/nobackup/archive/CognateMT/spm_models/fr-mfe_en/fr-mfe_en/fr-mfe_en
src: fr
test_batch_size: 128
test_checkpoint: /home/hatch5o6/nobackup/archive/CognateMT/PredictCognates/mfe-en/PRETRAIN.fr-en_TRIAL_s=1000/checkpoints/epoch=3-step=68362-val_loss=0.8824.ckpt
test_data: /home/hatch5o6/Cognate/code/NMT/data/PLAIN/fr-en_dev_test/test.csv
tgt: en
train_batch_size: 128
train_data: /home/hatch5o6/Cognate/code/NMT/data/PLAIN/fr-en/train.no_overlap_v1.csv
upsample: false
val_batch_size: 128
val_data: /home/hatch5o6/Cognate/code/NMT/data/PLAIN/fr-en_dev_test/val.no_overlap_v1.csv
val_interval: 0.25
verbose: false
warmup_steps: 5000.0
weight_decay: 0.01
